### ISSUE TITLE
Does Xvfb need to be installed if running mShots on Ubuntu

### ISSUE THREAD

**Issue by lukecav** [Automattic/mShots#13]
> The virtual frame buffer Kernel module (VFB) is required on your distro.
https://github.com/Automattic/mShots#installation

When running mShots on a Ubuntu OS would Xvfb need to be installed?
https://www.howtoinstall.me/ubuntu/18-04/xvfb/

**Comment by darthhexx** [comment]
Xvfb is only required if you aren't running an X-server.
