### ISSUE TITLE
Taller screenshots

### ISSUE THREAD

**Issue by simison** [Automattic/mShots#16]
### Problem

It's hard to produce "tall" screenshots with mshots. It's possible to adjust `w` image width, `h`  image height, `vpw` viewport width, `vph` viewport height and by tweaking those I was able to produce:

<img src="https://user-images.githubusercontent.com/87168/77934404-b84fae00-72b8-11ea-8ea4-d23aa13ad5f4.jpg" alt="" width="200">

[`?w=800&h=1200&vpw=960&vph=1200`](https://s.wordpress.com/mshots/v1/https%3A%2F%2Fpublic-api.wordpress.com%2Frest%2Fv1%2Ftemplate%2Fdemo%2Frivington%2Frivington?w=800&h=1200&vpw=960&vph=1200)

But it started to clip it out from sides when I was pushing it taller:

<img src="https://user-images.githubusercontent.com/87168/77921669-bd0c6600-72a8-11ea-8d95-517310d3573a.png" alt="" width="200">

[`?w=600&h=1200&vpw=960&vph=1200`](https://s.wordpress.com/mshots/v1/https%3A%2F%2Fpublic-api.wordpress.com%2Frest%2Fv1%2Ftemplate%2Fdemo%2Frivington%2Frivington?w=600&h=1200&vpw=960&vph=1200)

We'd need something like this:

<img src="https://user-images.githubusercontent.com/87168/78040681-72f2b580-7378-11ea-8c67-80a5d5980484.png" alt="" width="200">

...or even full page if it's easier:

<img src="https://user-images.githubusercontent.com/87168/78040686-7423e280-7378-11ea-9e4d-e281527bf73d.jpg" alt="" width="200">

See [that page in browser](https://public-api.wordpress.com/rest/v1/template/demo/rivington/rivington/)

We'll need tall screenshots of theme sites in new .com onboarding flow; https://github.com/Automattic/wp-calypso/issues/40564

### Solutions

- There's [maximum cap of 1200px](https://github.com/Automattic/mShots/blob/c141f2058027c849a82c1e4792ff7baf8a0bb098/public_html/class-mshots.php#L15) on viewport height. Can we create taller screenshots by increasing the cap?
  - What would happen if the site is shorter than what we set as cap?

- Can we grab full browser screenshots by setting viewport width and height to 0 and setting `fullPage:true`?
  - [I tested and confirmed it would grab full page screenshot](https://github.com/Automattic/mShots/pull/15)
  - Might cause trouble with extremely tall sites or sites that infinite-load content on scroll
  - We really just need taller portion of the site, not necessarily the full page.
  - To achieve this, we could allow `0` for `vph`/`vpw`. Setting those to zero would then set `fullPage:true` as well. Alternatively, we could have simpler API by needing to just add `?full-page` in URL which would then set everything needed.
   - Even for "full page" screenshots it would be good to have maximum cap. In fact it could be useful to have API that tells "grab a full page screenshot, but no more than than X"

cc @johnHackworth  @darthhexx

**Comment by andrewserong** [comment]
Just dusting off this issue. Looks like there's a potential solution to this already, discussed in p3topS-Ia-p2#comment-2967

**Comment by ramonjd** [comment]
we're tracking this work as part of pbAok1-1PR-p2#comment-3724
