### ISSUE TITLE
Javascript doesn't execute on page load

### ISSUE THREAD

**Issue by BinaryMoon** [Automattic/mShots#2]
Javascript doesn't seem to work on page load - and so a lot of sites that use it don't look right. In particular sites that rely on JQuery Masonry for post layout.

You can see an example here:
https://s0.wordpress.com/mshots/v1/andreahausmannphotography.wordpress.com?w=400&h=300

with the original site here:
http://andreahausmannphotography.wordpress.com/

I've seen javascript working on other website screenshot capture apps so I know it's possible - I just don't know what's involved. Would be great if it could be made to work on wp.com so that my theme screenshots look good.

**Comment by darthhexx** [comment]
Hi, apologies for the late comeback :/ I am not seeing any difference between the screenshot and the site itself. Are you still experiencing the issue?

**Comment by BinaryMoon** [comment]
Looks like they've changed site since I reported this :)

This one won't change since it's a theme demo:
https://s0.wordpress.com/mshots/v1/puzzledemo.wordpress.com?w=400&h=300
original site: https://puzzledemo.wordpress.com

**Comment by darthhexx** [comment]
Unfortunately even the latest version of QtWebKit (5.7) does not render the page correctly. Fixing this one will need to wait until the QtWebEngine version of mShots is released.

**Comment by BinaryMoon** [comment]
That's a shame - so I assume the other services using this are using a different tech?

Is switching to QtWebEngine something that's planned?

There's a lot of masonry themes on wordpress.com - and with the move to using REST and react it's going to be needed even more in the future I imagine.

**Comment by darthhexx** [comment]
It is planned, although there is no hard date set for it as yet.

**Comment by BinaryMoon** [comment]
Nice - is there a ticket or something I can follow so I can see when it's done?

**Comment by darthhexx** [comment]
I'll let you know here, once it has any resource allocation and has a target date.

**Comment by darthhexx** [comment]
@BinaryMoon, as of #8 the app has been switched over to using puppetter, which uses headless chrome as the rendering engine. This change fixes the above JS issues.

**Comment by darthhexx** [comment]
If only a day had 124 hours in it ;)
