### ISSUE TITLE
User-agent value can create browser warnings on some sites

### ISSUE THREAD

**Issue by ryanmarkel** [Automattic/mShots#4]
mSshots sets user-agent to Firefox 21 here: https://github.com/Automattic/mShots/blob/1582561027ba1e27aa982d9faaa4b26ff29c04b9/config/mshots.conf#L2

This is causing "outdated browser" warnings like this:

http://s.wp.com/mshots/v1/http%3A%2F%2Fwww.musiciansfriend.com%2Fstupid%232016620-14

**Comment by darthhexx** [comment]
This has been resolved by an upgrade to the Qt 5.7 libraries and an update to the UA.
