### ISSUE TITLE
Refresh Screenshot

### ISSUE THREAD

**Issue by mediageni** [Automattic/mShots#84]
Hi,

Is it possible to trigger a refresh for generating the screenshot?
For example if I change profile picture or website page, It is always showing an old image.

Much thanks

**Comment by mediageni** [comment]
Already figured out!

**Comment by Awilson089** [comment]
@mediageni What was the solution to this? 🙂

**Comment by mediageni** [comment]
@Awilson089  add &requeue=true as parameter
